[versions]
hibernate = "7.1.7.Final"
redisson = "3.45.0"
kryo = "5.5.0"
mariadb = "3.5.9"

[libraries]
hibernate-core = { module = "org.hibernate.orm:hibernate-core", version.ref = "hibernate" }
hibernate-hikari = { module = "org.hibernate.orm:hibernate-hikaricp", version.ref = "hibernate" }
redisson = { module = "org.redisson:redisson", version.ref = "redisson" }
kryo = { module = "com.esotericsoftware:kryo", version.ref = "kryo" }
mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }